// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXF0HW24L8CyMIyBR7H4MNw8qHbJl5UHI',
    appId: '1:125106578576:web:2219c26db3219ada2f6415',
    messagingSenderId: '125106578576',
    projectId: 'dispatchmanagement-e11b7',
    authDomain: 'dispatchmanagement-e11b7.firebaseapp.com',
    databaseURL: 'https://dispatchmanagement-e11b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dispatchmanagement-e11b7.firebasestorage.app',
    measurementId: 'G-0KWVRH4SWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3H9gtQln-UGEhLpLcr0H0GjLDW64u1C4',
    appId: '1:125106578576:android:e7facd0a7ae78d7e2f6415',
    messagingSenderId: '125106578576',
    projectId: 'dispatchmanagement-e11b7',
    databaseURL: 'https://dispatchmanagement-e11b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dispatchmanagement-e11b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo1_fSky_7RquhFoAR_IFgBx4nohiEgGA',
    appId: '1:125106578576:ios:f90476f84cd77c262f6415',
    messagingSenderId: '125106578576',
    projectId: 'dispatchmanagement-e11b7',
    databaseURL: 'https://dispatchmanagement-e11b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dispatchmanagement-e11b7.firebasestorage.app',
    iosBundleId: 'com.example.dispatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo1_fSky_7RquhFoAR_IFgBx4nohiEgGA',
    appId: '1:125106578576:ios:f90476f84cd77c262f6415',
    messagingSenderId: '125106578576',
    projectId: 'dispatchmanagement-e11b7',
    databaseURL: 'https://dispatchmanagement-e11b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dispatchmanagement-e11b7.firebasestorage.app',
    iosBundleId: 'com.example.dispatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXF0HW24L8CyMIyBR7H4MNw8qHbJl5UHI',
    appId: '1:125106578576:web:036630ae6b3c614e2f6415',
    messagingSenderId: '125106578576',
    projectId: 'dispatchmanagement-e11b7',
    authDomain: 'dispatchmanagement-e11b7.firebaseapp.com',
    databaseURL: 'https://dispatchmanagement-e11b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dispatchmanagement-e11b7.firebasestorage.app',
    measurementId: 'G-SWDFWXKKVK',
  );
}
